In [8]:
import torch

# 生成一个正太分布
a = torch.randn(2,3)
a.type()

# type(a)

'torch.FloatTensor'

In [9]:
# 在cpu上进行匹配检测
isinstance(a,torch.cuda.FloatTensor)

False

In [10]:
# 在cuda上进行监测  表示为true
a = a.cuda()
isinstance(a,torch.cuda.FloatTensor)

True

In [11]:
#  标量

torch.tensor(1.)

tensor(1.)

In [12]:
b= torch.tensor(1.1)
b.dim()

0

In [14]:
a = torch.randn(2,3)
print(a)

# 打印维度
print(a.dim())

# 打印shape
print(a.shape)

print(a.size(0))
print(a.size(1))
print(a.shape[1])

tensor([[ 0.2003,  0.9939,  1.3859],
        [ 1.5716,  0.2460, -0.1137]])
2
torch.Size([2, 3])
2
3
3


In [18]:
# 两张照片的 3通道的 28 x 28大小的照片
a = torch.rand(2,3,28,28)
# print(a)

# torch.Size([2, 3, 28, 28])
print(a.shape)

# 打印元素个数 4704
print(a.numel())

# 打印维度 4
print(a.dim())

torch.Size([2, 3, 28, 28])
4704
4


In [19]:
print(torch.tensor([1.2,3]).type())  # 默认参数类型

torch.FloatTensor


In [20]:
torch.full([2,3],7)

tensor([[7, 7, 7],
        [7, 7, 7]])

In [22]:
print(torch.arange(0,10,2))
print(torch.eye(3))

tensor([0, 2, 4, 6, 8])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [24]:
a = torch.rand(4,3,28,28)
print(a[0].shape)
print(a[0,0].shape)

torch.Size([3, 28, 28])
torch.Size([28, 28])


In [29]:
#  切片  从第一张图片开始 到第二张图片 但是不包含第二张图片
print(a[:2].shape)

# 通道数开始切片
print(a[:2,:1,:,:].shape)

# -1开始索引 取出最后一个channel
print(a[:2,-1:,:,:].shape)

torch.Size([2, 3, 28, 28])
torch.Size([2, 1, 28, 28])
torch.Size([2, 1, 28, 28])
